"""Initial migration

Revision ID: 68ca4f019cd6
Revises: 
Create Date: 2026-01-12 00:45:37.055808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ca4f019cd6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create tables
    op.create_table('departments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('departId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('departName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('departId', name=op.f('uq_departments_departId'))
    )
    op.create_index(op.f('ix_departments_departId'), 'departments', ['departId'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('userName', name=op.f('uq_users_userName'))
    )
    op.create_index(op.f('ix_users_userName'), 'users', ['userName'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('empName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('empAge', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('empSalary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('departId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('userName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    sa.UniqueConstraint('userName', name=op.f('uq_employees_userName'))
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)

    op.create_table('leaves',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('leave_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('userName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Leave_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leaves')),
    sa.UniqueConstraint('leave_id', name=op.f('uq_leaves_leave_id'))
    )
    op.create_index(op.f('ix_leaves_leave_id'), 'leaves', ['leave_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaves_leave_id'), table_name='leaves')
    op.drop_table('leaves')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_users_userName'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_departments_departId'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
