"""message

Revision ID: f6dccd4de24e
Revises: 5f6094689c72
Create Date: 2026-01-21 11:49:21.206298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6dccd4de24e'
down_revision: Union[str, Sequence[str], None] = '5f6094689c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaves_id'), table_name='leaves')
    op.drop_table('leaves')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('empName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('empAge', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('empSalary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('departId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('empGender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('userName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('employees_pkey')),
    sa.UniqueConstraint('userName', name=op.f('employees_userName_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('userName', name=op.f('users_userName_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('departId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('departName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('departments_pkey')),
    sa.UniqueConstraint('departId', name=op.f('departments_departId_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('leaves',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('leave_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('userName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Leave_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('leaves_pkey')),
    sa.UniqueConstraint('leave_id', name=op.f('leaves_leave_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_leaves_id'), 'leaves', ['id'], unique=False)
    # ### end Alembic commands ###
